---
name: Build - Ubuntu (dummy)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "src/**"

jobs:
  job:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        buildtype: [linux-release, linux-debug]
        include:
          - os: ubuntu-22.04
            triplet: x64-linux

    steps:
      - run: echo "This is a dummy job to satisfy branch protection checks"
      - name: Checkout repository
        uses: actions/checkout@main
