---
name: Build - Docker (dummy)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "src/**"

jobs:
  build_docker_x86:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a dummy job to satisfy branch protection checks"

  build_docker_arm:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a dummy job to satisfy branch protection checks"
