---
name: Build - Windows - CMake (dummy)
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "src/**"

jobs:
  job:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        buildtype: [windows-release]
        include:
          - os: windows-2022
            triplet: x64-windows-static
            packages: >
              sccache
    steps:
      - run: echo "This is a dummy job to satisfy branch protection checks"
