---
name: Clang-format (dummy)
on:
  pull_request:
    paths-ignore:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a dummy job to satisfy branch protection checks"
